# A class value's `new` and `raise k, s` that reach more than 64 initialize
# methods (#6179): every class the switch has an arm for is a target, so an
# appending initialize past the 64th still takes the caller's String. Each
# append is 100 bytes, so a copy could not pass by capacity.
class K0; def initialize(s) = (@n = s.size); end
class K1; def initialize(s) = (@n = s.size); end
class K2; def initialize(s) = (@n = s.size); end
class K3; def initialize(s) = (@n = s.size); end
class K4; def initialize(s) = (@n = s.size); end
class K5; def initialize(s) = (@n = s.size); end
class K6; def initialize(s) = (@n = s.size); end
class K7; def initialize(s) = (@n = s.size); end
class K8; def initialize(s) = (@n = s.size); end
class K9; def initialize(s) = (@n = s.size); end
class K10; def initialize(s) = (@n = s.size); end
class K11; def initialize(s) = (@n = s.size); end
class K12; def initialize(s) = (@n = s.size); end
class K13; def initialize(s) = (@n = s.size); end
class K14; def initialize(s) = (@n = s.size); end
class K15; def initialize(s) = (@n = s.size); end
class K16; def initialize(s) = (@n = s.size); end
class K17; def initialize(s) = (@n = s.size); end
class K18; def initialize(s) = (@n = s.size); end
class K19; def initialize(s) = (@n = s.size); end
class K20; def initialize(s) = (@n = s.size); end
class K21; def initialize(s) = (@n = s.size); end
class K22; def initialize(s) = (@n = s.size); end
class K23; def initialize(s) = (@n = s.size); end
class K24; def initialize(s) = (@n = s.size); end
class K25; def initialize(s) = (@n = s.size); end
class K26; def initialize(s) = (@n = s.size); end
class K27; def initialize(s) = (@n = s.size); end
class K28; def initialize(s) = (@n = s.size); end
class K29; def initialize(s) = (@n = s.size); end
class K30; def initialize(s) = (@n = s.size); end
class K31; def initialize(s) = (@n = s.size); end
class K32; def initialize(s) = (@n = s.size); end
class K33; def initialize(s) = (@n = s.size); end
class K34; def initialize(s) = (@n = s.size); end
class K35; def initialize(s) = (@n = s.size); end
class K36; def initialize(s) = (@n = s.size); end
class K37; def initialize(s) = (@n = s.size); end
class K38; def initialize(s) = (@n = s.size); end
class K39; def initialize(s) = (@n = s.size); end
class K40; def initialize(s) = (@n = s.size); end
class K41; def initialize(s) = (@n = s.size); end
class K42; def initialize(s) = (@n = s.size); end
class K43; def initialize(s) = (@n = s.size); end
class K44; def initialize(s) = (@n = s.size); end
class K45; def initialize(s) = (@n = s.size); end
class K46; def initialize(s) = (@n = s.size); end
class K47; def initialize(s) = (@n = s.size); end
class K48; def initialize(s) = (@n = s.size); end
class K49; def initialize(s) = (@n = s.size); end
class K50; def initialize(s) = (@n = s.size); end
class K51; def initialize(s) = (@n = s.size); end
class K52; def initialize(s) = (@n = s.size); end
class K53; def initialize(s) = (@n = s.size); end
class K54; def initialize(s) = (@n = s.size); end
class K55; def initialize(s) = (@n = s.size); end
class K56; def initialize(s) = (@n = s.size); end
class K57; def initialize(s) = (@n = s.size); end
class K58; def initialize(s) = (@n = s.size); end
class K59; def initialize(s) = (@n = s.size); end
class K60; def initialize(s) = (@n = s.size); end
class K61; def initialize(s) = (@n = s.size); end
class K62; def initialize(s) = (@n = s.size); end
class K63; def initialize(s) = (@n = s.size); end
class K64; def initialize(s) = (@n = s.size); end
class KA; def initialize(s) = (s << "!" * 100); end
ks = [K0, K1, K2, K3, K4, K5, K6, K7, K8, K9, K10, K11, K12, K13, K14, K15, K16, K17, K18, K19, K20, K21, K22, K23, K24, K25, K26, K27, K28, K29, K30, K31, K32, K33, K34, K35, K36, K37, K38, K39, K40, K41, K42, K43, K44, K45, K46, K47, K48, K49, K50, K51, K52, K53, K54, K55, K56, K57, K58, K59, K60, K61, K62, K63, K64, KA]
t = +"a"; ks[65 + ARGV.size].new(t); p t.size
class E0 < StandardError; def initialize(m) = super(m.to_s); end
class E1 < StandardError; def initialize(m) = super(m.to_s); end
class E2 < StandardError; def initialize(m) = super(m.to_s); end
class E3 < StandardError; def initialize(m) = super(m.to_s); end
class E4 < StandardError; def initialize(m) = super(m.to_s); end
class E5 < StandardError; def initialize(m) = super(m.to_s); end
class E6 < StandardError; def initialize(m) = super(m.to_s); end
class E7 < StandardError; def initialize(m) = super(m.to_s); end
class E8 < StandardError; def initialize(m) = super(m.to_s); end
class E9 < StandardError; def initialize(m) = super(m.to_s); end
class E10 < StandardError; def initialize(m) = super(m.to_s); end
class E11 < StandardError; def initialize(m) = super(m.to_s); end
class E12 < StandardError; def initialize(m) = super(m.to_s); end
class E13 < StandardError; def initialize(m) = super(m.to_s); end
class E14 < StandardError; def initialize(m) = super(m.to_s); end
class E15 < StandardError; def initialize(m) = super(m.to_s); end
class E16 < StandardError; def initialize(m) = super(m.to_s); end
class E17 < StandardError; def initialize(m) = super(m.to_s); end
class E18 < StandardError; def initialize(m) = super(m.to_s); end
class E19 < StandardError; def initialize(m) = super(m.to_s); end
class E20 < StandardError; def initialize(m) = super(m.to_s); end
class E21 < StandardError; def initialize(m) = super(m.to_s); end
class E22 < StandardError; def initialize(m) = super(m.to_s); end
class E23 < StandardError; def initialize(m) = super(m.to_s); end
class E24 < StandardError; def initialize(m) = super(m.to_s); end
class E25 < StandardError; def initialize(m) = super(m.to_s); end
class E26 < StandardError; def initialize(m) = super(m.to_s); end
class E27 < StandardError; def initialize(m) = super(m.to_s); end
class E28 < StandardError; def initialize(m) = super(m.to_s); end
class E29 < StandardError; def initialize(m) = super(m.to_s); end
class E30 < StandardError; def initialize(m) = super(m.to_s); end
class E31 < StandardError; def initialize(m) = super(m.to_s); end
class E32 < StandardError; def initialize(m) = super(m.to_s); end
class E33 < StandardError; def initialize(m) = super(m.to_s); end
class E34 < StandardError; def initialize(m) = super(m.to_s); end
class E35 < StandardError; def initialize(m) = super(m.to_s); end
class E36 < StandardError; def initialize(m) = super(m.to_s); end
class E37 < StandardError; def initialize(m) = super(m.to_s); end
class E38 < StandardError; def initialize(m) = super(m.to_s); end
class E39 < StandardError; def initialize(m) = super(m.to_s); end
class E40 < StandardError; def initialize(m) = super(m.to_s); end
class E41 < StandardError; def initialize(m) = super(m.to_s); end
class E42 < StandardError; def initialize(m) = super(m.to_s); end
class E43 < StandardError; def initialize(m) = super(m.to_s); end
class E44 < StandardError; def initialize(m) = super(m.to_s); end
class E45 < StandardError; def initialize(m) = super(m.to_s); end
class E46 < StandardError; def initialize(m) = super(m.to_s); end
class E47 < StandardError; def initialize(m) = super(m.to_s); end
class E48 < StandardError; def initialize(m) = super(m.to_s); end
class E49 < StandardError; def initialize(m) = super(m.to_s); end
class E50 < StandardError; def initialize(m) = super(m.to_s); end
class E51 < StandardError; def initialize(m) = super(m.to_s); end
class E52 < StandardError; def initialize(m) = super(m.to_s); end
class E53 < StandardError; def initialize(m) = super(m.to_s); end
class E54 < StandardError; def initialize(m) = super(m.to_s); end
class E55 < StandardError; def initialize(m) = super(m.to_s); end
class E56 < StandardError; def initialize(m) = super(m.to_s); end
class E57 < StandardError; def initialize(m) = super(m.to_s); end
class E58 < StandardError; def initialize(m) = super(m.to_s); end
class E59 < StandardError; def initialize(m) = super(m.to_s); end
class E60 < StandardError; def initialize(m) = super(m.to_s); end
class E61 < StandardError; def initialize(m) = super(m.to_s); end
class E62 < StandardError; def initialize(m) = super(m.to_s); end
class E63 < StandardError; def initialize(m) = super(m.to_s); end
class E64 < StandardError; def initialize(m) = super(m.to_s); end
class EA < StandardError; def initialize(m) = (m << "!" * 100; super("x")); end
es = [E0, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22, E23, E24, E25, E26, E27, E28, E29, E30, E31, E32, E33, E34, E35, E36, E37, E38, E39, E40, E41, E42, E43, E44, E45, E46, E47, E48, E49, E50, E51, E52, E53, E54, E55, E56, E57, E58, E59, E60, E61, E62, E63, E64, EA]
m = +"b"
begin; raise es[65 + ARGV.size], m; rescue EA; end
p m.size
