#!/usr/bin/env ruby
# gen_manifest.rb -- regenerate an expectations manifest from a full
# measurement, applying the by-design ledger.
#
# Usage: ruby tools/rubyspec/gen_manifest.rb RESULTS_TSV > expectations/X.tsv
#
# A REJECT whose diagnostic matches a BYDESIGN pattern becomes
# REJECT-BYDESIGN: a permanent, deliberate exclusion (spinel is a subset;
# see docs/limitations.md "Fundamental limits") that leaves the adjusted
# score's denominator. An ERROR whose last line matches a BYDESIGN_ERROR
# pattern becomes ERROR-BYDESIGN the same way. Everything else keeps its
# measured status; frontier REJECTs stay plain REJECT so the ranking keeps
# pointing at them.
#
# Keep this list conservative: by-design is a declaration that the example
# will NEVER pass, so when in doubt leave it on the frontier.

BYDESIGN = [
  /eval of a runtime string/,            # needs a runtime parser (AOT-fundamental)
  /singleton class on arbitrary object/, # per-object method tables vs direct C calls
  # general reflection: Method/UnboundMethod objects and method-table queries
  # (limitations.md: ivars are struct offsets, DCE strips method names)
  /`(instance_method|instance_methods|private_instance_methods|public_instance_methods|protected_instance_methods|owner|unbind)`/,
  # Encoding machinery: one internal representation, no transcoding tables
  /`(default_external|default_internal|force_encoding)`/,
  # Method-table surgery: methods compile to direct C calls, so there is no
  # runtime table to remove an entry from (limitations.md "By design")
  /Module#(undef_method|remove_method|remove_class_variable) is not supported/,
  # the rest of limitations.md's "Fundamental limits" table, in the words the
  # compiler refuses them with: scope-keyed dispatch, a class built at run
  # time, a per-object method table, a reified local scope
  /Refinements are not supported/,
  /Class\.new\(parent\) \{ \.\.\. \} is not supported/,
  /Object#(singleton_class|define_singleton_method|extend) is not supported/,
  /undefined local variable or method 'binding'/,
  # limitations.md "By design": a Ruby 2.x keyword shim, and the string-named
  # Struct form
  /Proc#ruby2_keywords is not supported/,
  /Struct\.new with a string name/
].freeze

# An example that compiles but dies on a reflection call: the method-table
# queries and Method/UnboundMethod getters spinel answers with NoMethodError
# at run time (limitations.md: DCE strips method names). ruby/spec asks them
# to check aliases and visibility -- `Float.instance_method(:angle).should ==
# Float.instance_method(:arg)`, `Kernel.private_instance_methods(false)
# .should.include?(:Array)` -- so they would otherwise sit on the frontier.
BYDESIGN_ERROR = [
  /undefined method '(instance_method|public_instance_method|instance_methods|private_instance_methods|public_instance_methods|protected_instance_methods|methods|public_methods|private_methods|protected_methods|singleton_methods|owner|unbind)' for /
].freeze

results = ARGV[0] or abort "usage: gen_manifest.rb RESULTS_TSV"

# read as bytes: an ERROR row carries the last line the example printed,
# which need not be valid in the locale's encoding (or in any)
rows = File.readlines(results, mode: "rb").map { |l| l.chomp.split("\t", 3) }

puts "# ruby/spec expectations manifest -- generated by gen_manifest.rb from a"
puts "# full measurement at RUBYSPEC_REV (see Makefile). One row per example:"
puts "# name<TAB>status. PASS rows are the retention gate's contract"
puts "# (make rubyspec-gate); *-BYDESIGN rows are permanent exclusions"
puts "# (docs/limitations.md); the rest record the frontier. Regenerate"
puts "# deliberately, reviewing the diff, never by hand."

counts = Hash.new(0)
rows.each do |name, status, detail|
  next unless name && status
  if status == "REJECT" && detail && BYDESIGN.any? { |re| re =~ detail }
    status = "REJECT-BYDESIGN"
  elsif status == "ERROR" && detail && BYDESIGN_ERROR.any? { |re| re =~ detail }
    status = "ERROR-BYDESIGN"
  end
  counts[status] += 1
  puts "#{name}\t#{status}"
end

pass = counts["PASS"]
bydesign = counts["REJECT-BYDESIGN"] + counts["ERROR-BYDESIGN"]
skew = counts["HARNESS-SKEW"]
total = counts.values.sum
denom = total - bydesign - skew
warn "manifest: #{pass} PASS / #{counts["FAIL"]} FAIL / #{counts["REJECT"]} REJECT " \
     "/ #{counts["REJECT-BYDESIGN"]} REJECT-BYDESIGN / #{counts["ERROR"]} ERROR " \
     "/ #{counts["ERROR-BYDESIGN"]} ERROR-BYDESIGN / #{skew} SKEW"
warn format("adjusted score: %d/%d = %.1f%% (denominator excludes by-design and skew)",
            pass, denom, 100.0 * pass / denom)
