# Generated by gen_accessors.py -- the typed accessor families of FFI::AbstractMemory.
# Do not edit by hand.
module FFI
  class AbstractMemory
    def get_int8(off) = Native.get_int(__addr(off, 1), Type::K_I8)
    def put_int8(off, v)
      Native.put_int(__addr(off, 1), Type::K_I8, Type.int_arg(v))
      self
    end
    def read_int8 = get_int8(0)
    def write_int8(v) = put_int8(0, v)
    def get_array_of_int8(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 1, 1), Type::K_I8)
        i += 1
      end
      a
    end
    def put_array_of_int8(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 1, 1), Type::K_I8, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_int8(count) = get_array_of_int8(0, count)
    def write_array_of_int8(ary) = put_array_of_int8(0, ary)
    def get_uint8(off) = Native.get_int(__addr(off, 1), Type::K_U8)
    def put_uint8(off, v)
      Native.put_int(__addr(off, 1), Type::K_U8, Type.int_arg(v))
      self
    end
    def read_uint8 = get_uint8(0)
    def write_uint8(v) = put_uint8(0, v)
    def get_array_of_uint8(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 1, 1), Type::K_U8)
        i += 1
      end
      a
    end
    def put_array_of_uint8(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 1, 1), Type::K_U8, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_uint8(count) = get_array_of_uint8(0, count)
    def write_array_of_uint8(ary) = put_array_of_uint8(0, ary)
    def get_int16(off) = Native.get_int(__addr(off, 2), Type::K_I16)
    def put_int16(off, v)
      Native.put_int(__addr(off, 2), Type::K_I16, Type.int_arg(v))
      self
    end
    def read_int16 = get_int16(0)
    def write_int16(v) = put_int16(0, v)
    def get_array_of_int16(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 2, 2), Type::K_I16)
        i += 1
      end
      a
    end
    def put_array_of_int16(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 2, 2), Type::K_I16, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_int16(count) = get_array_of_int16(0, count)
    def write_array_of_int16(ary) = put_array_of_int16(0, ary)
    def get_uint16(off) = Native.get_int(__addr(off, 2), Type::K_U16)
    def put_uint16(off, v)
      Native.put_int(__addr(off, 2), Type::K_U16, Type.int_arg(v))
      self
    end
    def read_uint16 = get_uint16(0)
    def write_uint16(v) = put_uint16(0, v)
    def get_array_of_uint16(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 2, 2), Type::K_U16)
        i += 1
      end
      a
    end
    def put_array_of_uint16(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 2, 2), Type::K_U16, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_uint16(count) = get_array_of_uint16(0, count)
    def write_array_of_uint16(ary) = put_array_of_uint16(0, ary)
    def get_int32(off) = Native.get_int(__addr(off, 4), Type::K_I32)
    def put_int32(off, v)
      Native.put_int(__addr(off, 4), Type::K_I32, Type.int_arg(v))
      self
    end
    def read_int32 = get_int32(0)
    def write_int32(v) = put_int32(0, v)
    def get_array_of_int32(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 4, 4), Type::K_I32)
        i += 1
      end
      a
    end
    def put_array_of_int32(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 4, 4), Type::K_I32, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_int32(count) = get_array_of_int32(0, count)
    def write_array_of_int32(ary) = put_array_of_int32(0, ary)
    def get_uint32(off) = Native.get_int(__addr(off, 4), Type::K_U32)
    def put_uint32(off, v)
      Native.put_int(__addr(off, 4), Type::K_U32, Type.int_arg(v))
      self
    end
    def read_uint32 = get_uint32(0)
    def write_uint32(v) = put_uint32(0, v)
    def get_array_of_uint32(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 4, 4), Type::K_U32)
        i += 1
      end
      a
    end
    def put_array_of_uint32(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 4, 4), Type::K_U32, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_uint32(count) = get_array_of_uint32(0, count)
    def write_array_of_uint32(ary) = put_array_of_uint32(0, ary)
    def get_int64(off) = Native.get_int(__addr(off, 8), Type::K_I64)
    def put_int64(off, v)
      Native.put_int(__addr(off, 8), Type::K_I64, Type.int_arg(v))
      self
    end
    def read_int64 = get_int64(0)
    def write_int64(v) = put_int64(0, v)
    def get_array_of_int64(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 8, 8), Type::K_I64)
        i += 1
      end
      a
    end
    def put_array_of_int64(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 8, 8), Type::K_I64, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_int64(count) = get_array_of_int64(0, count)
    def write_array_of_int64(ary) = put_array_of_int64(0, ary)
    def get_uint64(off) = Native.get_int(__addr(off, 8), Type::K_U64)
    def put_uint64(off, v)
      Native.put_int(__addr(off, 8), Type::K_U64, Type.int_arg(v))
      self
    end
    def read_uint64 = get_uint64(0)
    def write_uint64(v) = put_uint64(0, v)
    def get_array_of_uint64(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 8, 8), Type::K_U64)
        i += 1
      end
      a
    end
    def put_array_of_uint64(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 8, 8), Type::K_U64, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_uint64(count) = get_array_of_uint64(0, count)
    def write_array_of_uint64(ary) = put_array_of_uint64(0, ary)
    def get_char(off) = Native.get_int(__addr(off, 1), Type::K_I8)
    def put_char(off, v)
      Native.put_int(__addr(off, 1), Type::K_I8, Type.int_arg(v))
      self
    end
    def read_char = get_char(0)
    def write_char(v) = put_char(0, v)
    def get_array_of_char(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 1, 1), Type::K_I8)
        i += 1
      end
      a
    end
    def put_array_of_char(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 1, 1), Type::K_I8, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_char(count) = get_array_of_char(0, count)
    def write_array_of_char(ary) = put_array_of_char(0, ary)
    def get_uchar(off) = Native.get_int(__addr(off, 1), Type::K_U8)
    def put_uchar(off, v)
      Native.put_int(__addr(off, 1), Type::K_U8, Type.int_arg(v))
      self
    end
    def read_uchar = get_uchar(0)
    def write_uchar(v) = put_uchar(0, v)
    def get_array_of_uchar(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 1, 1), Type::K_U8)
        i += 1
      end
      a
    end
    def put_array_of_uchar(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 1, 1), Type::K_U8, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_uchar(count) = get_array_of_uchar(0, count)
    def write_array_of_uchar(ary) = put_array_of_uchar(0, ary)
    def get_short(off) = Native.get_int(__addr(off, 2), Type::K_I16)
    def put_short(off, v)
      Native.put_int(__addr(off, 2), Type::K_I16, Type.int_arg(v))
      self
    end
    def read_short = get_short(0)
    def write_short(v) = put_short(0, v)
    def get_array_of_short(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 2, 2), Type::K_I16)
        i += 1
      end
      a
    end
    def put_array_of_short(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 2, 2), Type::K_I16, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_short(count) = get_array_of_short(0, count)
    def write_array_of_short(ary) = put_array_of_short(0, ary)
    def get_ushort(off) = Native.get_int(__addr(off, 2), Type::K_U16)
    def put_ushort(off, v)
      Native.put_int(__addr(off, 2), Type::K_U16, Type.int_arg(v))
      self
    end
    def read_ushort = get_ushort(0)
    def write_ushort(v) = put_ushort(0, v)
    def get_array_of_ushort(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 2, 2), Type::K_U16)
        i += 1
      end
      a
    end
    def put_array_of_ushort(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 2, 2), Type::K_U16, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_ushort(count) = get_array_of_ushort(0, count)
    def write_array_of_ushort(ary) = put_array_of_ushort(0, ary)
    def get_int(off) = Native.get_int(__addr(off, 4), Type::K_I32)
    def put_int(off, v)
      Native.put_int(__addr(off, 4), Type::K_I32, Type.int_arg(v))
      self
    end
    def read_int = get_int(0)
    def write_int(v) = put_int(0, v)
    def get_array_of_int(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 4, 4), Type::K_I32)
        i += 1
      end
      a
    end
    def put_array_of_int(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 4, 4), Type::K_I32, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_int(count) = get_array_of_int(0, count)
    def write_array_of_int(ary) = put_array_of_int(0, ary)
    def get_uint(off) = Native.get_int(__addr(off, 4), Type::K_U32)
    def put_uint(off, v)
      Native.put_int(__addr(off, 4), Type::K_U32, Type.int_arg(v))
      self
    end
    def read_uint = get_uint(0)
    def write_uint(v) = put_uint(0, v)
    def get_array_of_uint(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 4, 4), Type::K_U32)
        i += 1
      end
      a
    end
    def put_array_of_uint(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 4, 4), Type::K_U32, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_uint(count) = get_array_of_uint(0, count)
    def write_array_of_uint(ary) = put_array_of_uint(0, ary)
    def get_long(off) = Native.get_int(__addr(off, 8), Type::K_I64)
    def put_long(off, v)
      Native.put_int(__addr(off, 8), Type::K_I64, Type.int_arg(v))
      self
    end
    def read_long = get_long(0)
    def write_long(v) = put_long(0, v)
    def get_array_of_long(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 8, 8), Type::K_I64)
        i += 1
      end
      a
    end
    def put_array_of_long(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 8, 8), Type::K_I64, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_long(count) = get_array_of_long(0, count)
    def write_array_of_long(ary) = put_array_of_long(0, ary)
    def get_ulong(off) = Native.get_int(__addr(off, 8), Type::K_U64)
    def put_ulong(off, v)
      Native.put_int(__addr(off, 8), Type::K_U64, Type.int_arg(v))
      self
    end
    def read_ulong = get_ulong(0)
    def write_ulong(v) = put_ulong(0, v)
    def get_array_of_ulong(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 8, 8), Type::K_U64)
        i += 1
      end
      a
    end
    def put_array_of_ulong(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 8, 8), Type::K_U64, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_ulong(count) = get_array_of_ulong(0, count)
    def write_array_of_ulong(ary) = put_array_of_ulong(0, ary)
    def get_long_long(off) = Native.get_int(__addr(off, 8), Type::K_I64)
    def put_long_long(off, v)
      Native.put_int(__addr(off, 8), Type::K_I64, Type.int_arg(v))
      self
    end
    def read_long_long = get_long_long(0)
    def write_long_long(v) = put_long_long(0, v)
    def get_array_of_long_long(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 8, 8), Type::K_I64)
        i += 1
      end
      a
    end
    def put_array_of_long_long(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 8, 8), Type::K_I64, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_long_long(count) = get_array_of_long_long(0, count)
    def write_array_of_long_long(ary) = put_array_of_long_long(0, ary)
    def get_ulong_long(off) = Native.get_int(__addr(off, 8), Type::K_U64)
    def put_ulong_long(off, v)
      Native.put_int(__addr(off, 8), Type::K_U64, Type.int_arg(v))
      self
    end
    def read_ulong_long = get_ulong_long(0)
    def write_ulong_long(v) = put_ulong_long(0, v)
    def get_array_of_ulong_long(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_int(__addr(off + i * 8, 8), Type::K_U64)
        i += 1
      end
      a
    end
    def put_array_of_ulong_long(off, ary)
      i = 0
      while i < ary.size
        Native.put_int(__addr(off + i * 8, 8), Type::K_U64, Type.int_arg(ary[i]))
        i += 1
      end
      self
    end
    def read_array_of_ulong_long(count) = get_array_of_ulong_long(0, count)
    def write_array_of_ulong_long(ary) = put_array_of_ulong_long(0, ary)
    def get_float32(off) = Native.get_float(__addr(off, 4), Type::K_F32)
    def put_float32(off, v)
      Native.put_float(__addr(off, 4), Type::K_F32, v.to_f)
      self
    end
    def read_float32 = get_float32(0)
    def write_float32(v) = put_float32(0, v)
    def get_array_of_float32(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_float(__addr(off + i * 4, 4), Type::K_F32)
        i += 1
      end
      a
    end
    def put_array_of_float32(off, ary)
      i = 0
      while i < ary.size
        Native.put_float(__addr(off + i * 4, 4), Type::K_F32, ary[i].to_f)
        i += 1
      end
      self
    end
    def read_array_of_float32(count) = get_array_of_float32(0, count)
    def write_array_of_float32(ary) = put_array_of_float32(0, ary)
    def get_float(off) = Native.get_float(__addr(off, 4), Type::K_F32)
    def put_float(off, v)
      Native.put_float(__addr(off, 4), Type::K_F32, v.to_f)
      self
    end
    def read_float = get_float(0)
    def write_float(v) = put_float(0, v)
    def get_array_of_float(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_float(__addr(off + i * 4, 4), Type::K_F32)
        i += 1
      end
      a
    end
    def put_array_of_float(off, ary)
      i = 0
      while i < ary.size
        Native.put_float(__addr(off + i * 4, 4), Type::K_F32, ary[i].to_f)
        i += 1
      end
      self
    end
    def read_array_of_float(count) = get_array_of_float(0, count)
    def write_array_of_float(ary) = put_array_of_float(0, ary)
    def get_float64(off) = Native.get_float(__addr(off, 8), Type::K_F64)
    def put_float64(off, v)
      Native.put_float(__addr(off, 8), Type::K_F64, v.to_f)
      self
    end
    def read_float64 = get_float64(0)
    def write_float64(v) = put_float64(0, v)
    def get_array_of_float64(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_float(__addr(off + i * 8, 8), Type::K_F64)
        i += 1
      end
      a
    end
    def put_array_of_float64(off, ary)
      i = 0
      while i < ary.size
        Native.put_float(__addr(off + i * 8, 8), Type::K_F64, ary[i].to_f)
        i += 1
      end
      self
    end
    def read_array_of_float64(count) = get_array_of_float64(0, count)
    def write_array_of_float64(ary) = put_array_of_float64(0, ary)
    def get_double(off) = Native.get_float(__addr(off, 8), Type::K_F64)
    def put_double(off, v)
      Native.put_float(__addr(off, 8), Type::K_F64, v.to_f)
      self
    end
    def read_double = get_double(0)
    def write_double(v) = put_double(0, v)
    def get_array_of_double(off, count)
      a = []
      i = 0
      while i < count
        a << Native.get_float(__addr(off + i * 8, 8), Type::K_F64)
        i += 1
      end
      a
    end
    def put_array_of_double(off, ary)
      i = 0
      while i < ary.size
        Native.put_float(__addr(off + i * 8, 8), Type::K_F64, ary[i].to_f)
        i += 1
      end
      self
    end
    def read_array_of_double(count) = get_array_of_double(0, count)
    def write_array_of_double(ary) = put_array_of_double(0, ary)
  end
end
