# Regenerates lib/sp_encoding_names.h from the running CRuby:
#
#   ruby --disable-gems tools/gen_encoding_names.rb
#
# Every encoding name and alias Encoding.find accepts, with the name of the
# encoding it answers (Encoding.find matches them case-insensitively). The
# special names (external, internal, locale, filesystem) are the runtime's.
pairs = Encoding.list.map { |e| [e.name, e.name] }
pairs += Encoding.aliases.reject { |a, _| %w[external internal locale filesystem].include?(a) }.to_a
pairs = pairs.uniq.sort
path = File.expand_path("../lib/sp_encoding_names.h", __dir__)
File.write(path, "/* Encoding names and aliases, CRuby #{RUBY_VERSION}. Generated by tools/gen_encoding_names.rb. */\n" +
                 pairs.map { |a, n| "  {#{a.dump}, #{n.dump}},\n" }.join)
