# The nil-method grid tests (test/nil_method_grid_<kind>.rb): each public
# method nil answers, called on a slot of one kind (String, user object,
# Array, Hash, Symbol, Range) that holds nil, the nil reaching it from a
# method's value, a local and a parameter's default. Each kind takes its own
# representation (a NULL pointer, a box), and every cell answers as nil does.
#
#   ruby tools/nil_method_grid_gen.rb test   # then regenerate the .expected
#                                            # files with CRuby
KINDS = { "string" => '"s"', "object" => 'K.new', "array" => '[1]', "hash" => '{a: 1}',
          "symbol" => ':q', "range" => '(1..2)' }
CALLS = ['!', '!= 1', '!~ /a/', '& true', '| false', '^ true', '<=> nil', '<=> 1', '== nil', '=== nil',
  '=~ /a/', '.class', '.dup', '.clone', '.eql?(nil)', '.equal?(nil)', '.freeze', '.frozen?',
  '.inspect', '.instance_of?(NilClass)', '.is_a?(NilClass)', '.itself', '.kind_of?(Comparable)',
  '.nil?', '.rationalize', '.respond_to?(:to_a)', '.tap { }', '.then { |q| q }', '.to_a', '.to_c',
  '.to_f', '.to_h', '.to_i', '.to_r', '.to_s', '.yield_self { |q| q.inspect }',
  '.instance_variables', '.object_id == nil.object_id']
out = ARGV[0] || "."
KINDS.each do |kn, ex|
  s = +"# Generated by tools/nil_method_grid_gen.rb: nil's #{CALLS.size} methods on a\n"
  s << "# #{kn} slot holding nil, the nil from a method's value, a local and a\n"
  s << "# parameter's default. Each answers as nil does in CRuby.\n"
  s << "class K; end\n"
  s << "def v(k) = k == 0 ? nil : #{ex}\n"
  s << "def w(x = nil) = x\n"
  s << "w(#{ex}) if ARGV.size == 9\n"
  s << "l = ARGV.size == 9 ? #{ex} : nil\n"
  CALLS.each_with_index do |cl, i|
    row = %w[v(0) l w].map do |recv|
      cl.start_with?(".") ? "#{recv}#{cl}" : (cl == "!" ? "!#{recv}" : "#{recv} #{cl}")
    end
    s << "p [#{i}, #{row.map { |e| "(#{e} rescue :raised)" }.join(', ')}]\n"
  end
  File.write(File.join(out, "nil_method_grid_#{kn}.rb"), s)
end
